sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product tstn-006
env:
  global:
    -
      # LTD_AWS_ID
      secure: FNFA+5BaGcPJl4FHoHm65xwtuMc4zBarDpnXfW6gfpElhra8XprZxpyBW+Z+jtz4jl1219To3xs6oQLnw/BJRMcLTCOr89mJdZhNdvdiXrKRuM3NglRX8uU+T32991lzeW2FEgzX+qzJTJZXcXnJZZ0+Rz67+1XxJ0u5QnvlcNiqtaMKh7Z0rbBOXXRG5fY6uDO6+HGZE+HUQu76lPjaWZ5F1LOC0+8Uo7oc3JRmX2gvtvWwFEZZo+Bp+o4I6OVTlyOG+dgPBkZ50DCjCwqqQDn520Skq0qA9Anr5MHq9hhwP3V4pg7QofZQezIqpJdeKPksKDH7VbafCkb8nqnV8Rnk01ebA5B5uncBe353pJC0Jo+RwA7QwHTjx/UUSSbfrtBe1SXFNOeq0GnO6LndE6uZx+6URoJgpHEUpXnPSwPS/v5xEwsN5q3w6LgsB9n7Ix0wfv2IDUan0mHL69uk0jxEQl4wdwRNfx8nTSdbisrfINnJizNU14DV09WlXg1DgGJUPQDdBU/3wvUpD2M1eDUU0capjIhR1+Qm62X17itA5r04gAyZhzmxvi7iVepzvCYh6CfWxKq4Z8nzv7Bm9sP66A/1TT/FUSGXx6B4CpDhC8ZcicSlmqJ1TXhcEhMjJHIgwNiVLJCEzvNJnTuo5KkeF7Mlmd+euUFj4boNrbE=
    -
      # LTD_AWS_SECRET
      secure: LKVthGgti6Ps+ATkNeslLwjYi8HjgGrXv6o9bR+SbS/8foBrjZbGF35uruIJfgkhlc3KP/1Zq+zs6+nwrhoL1RdZFtjZF2v846sk0bCDzTdmLlrLIhywiUyrkSudmEEWL2TYrz8+MdD2Kr7bL3xzM3gbdoUsUywabjWVFlCIWAA8RXnCk4xYYplK8MNwfnAbznWC4vQXFYUWd/cubA4Al9pcMRutm0rmWzkmOAuq1x9c+htjkZPkqQ3bhOLO3GBdLGwhc2nVYUwNvzftAj0PShbWW8iAMCDgw55HBAriXmaFY30m+Fw1+H9G6Pd7psMav7hUYqRUSVOq6D5aR2oEEqVED8ZUGLJaKP/3OLyjG4haeVCFUUISIRWDAZlwYLAlZHiGTF94jTyg+drL+ZVpkZUl4LACXVUrE8balECj/xAIBrhxtYQaB+oaZw7yKeu9uhxw7c7t7Tzn+D8jz5BbANmFI18PEfJP4L8+I+bNNdocadON5opCshZVOlk2UkUHEpVTC8y3p+MbaCeb1ZTJ/wAEt8Xi3KSNi3U20foLROkKxWjybHrt0vTcZqLLNL5Dj/FNyk9mjfg4WyDU3CYoF39CctLf+VOBXOmo9olBLExymW/k+vd2kjknEbuX14O2gssQqmweyrbCJEMVKMj+5jPETUgNunXQSQeBnakprAo=
    -
      # LTD_USERNAME
      secure: JYj43F/GLzlqa/N/LtN2C+KBIzO1HD6SUx4XdolcWl5dJ4ixGOPMqsevqtk0tm+aQh0gXWiW0mCPBfNj6TKXeLB1XGJO1d65oKTyaYtf/rCepcWIdTRQ6JfFtfgA1lA0AXg3GirfLiOm5WyYaSWVUNKjYaAUoOB4+BUGvdrpfcDfQKvujtXeLyfOvCdH208DeilBEgfdJU7+DDH7yojYMrozN7Z7aU5f+YAN+xrM0Xt5ll557eSH11rZNqBvy4+ybr0NcOmmxJNAsmGpJwG4fc7BTtHoFFL2YPl+Sb6VVK123pYrTKy81wCUGkKXS24b+8+Yd5ILAUKaoy9Lbo1pY1NUrVni3RuE4bHJQ2kWHmp/bvYREBlI0q1oJn+U5N8GGzZbDu4GDJlraw/Ckg28NIsRMxu7JPbKZgXh0IZWjxipMDG5dF5QYqh9dVww7/NF5zE9tH7hm5FlzX/iTw/NyZJbxbrfY4BgCKdwuFJI+qgHJ1pZAlKFdc+Y8nfYHu0cheGSN9JpNttofzJ/mRPGTPYbaHXQT9VfOBfk7ItfEVgBwZqzK2DiGZ9v+/evEkdvZsFidAdN1iu8jcmqDRw+/HMyvaEqx6WS0G4UhTr5D6nJu4HUnBatsf9A5s/EgKGMnbdN/xsGsbCynFgA6GfBnx6HgEdVV1OyNoTp1QI4tNk=
    -
      # LTD_PASSWORD
      secure: BVcEdX3LBhC/opxj/g+lHpr1THaYccM/VJ1xWZmP7NBvAhnBGXUeh3EwFWIlbJbnsyshCucdDwPi8mAZDLwU1k5c6Azjdgoj0WTJ8ktBgXru6qN4CnitU5ihRg+10kKq3nmF18wrKhbFvN4poYBGKoRqJ264ZPV4JOGrHbojve73JLGrFZqUTxZi3hPEgmv7RsWFlLW4yREnUrZJ8EcXeS8T9hipp2BgQovRZoEHrbgLORksa+OSN1WXewaWfB36815DWVz4tHKfarEq7cIlGyj21R1WYjEKb/N2yz9/r9HO2D4WwgIkDFsnyA9T5B9iAwMfT+wNTwXCrR7HaMiW7GXgCp7A8ALk0bu8HlR5KyCeyV95oL2T2fvEwyzDsESgrnODbAyD6zL0UtZS3AGo5aagLc2+ROrauogt55ZZJfmF05FAWEpKQUriQnojSsOQDGuCMc8gzcyBA324BypuWGARF+ffvR2QlvyKZk1oC8PL+r3qxAKzSXLm1kgEuMXgCnqskfa88ck3fviz2IGpGWxgVuZkG/a6r84O+SEdXUEkUU/xmNW9obdsq9X7/0qZeInig2kJ5NMXdrPWPKp5Rv2Sis48lI4GcI3TbbcY3i8Jcr0LglbUNy0FAWfvYj4sEIVkAQLV+hMREgroxCtqYYV/l4f/olICbWmBrDfs36M=
